### ISSUE TITLE
Upgrade to Leaflet v1.0

### ISSUE THREAD

**Issue by waldoj** [stamen/open-redistricting#39]
1.0 finally came out, and has a bajillion improvements, notably big speed improvements that might help us with large maps. This should be as simple as updating [`package.json`](https://github.com/stamen/usopendata/blob/master/package.json).

**Comment by ericsoco** [comment]
Closed via https://github.com/stamen/open-redistricting/commit/4b408f4bca72c841c16269ad604ba05168446061 and https://github.com/stamen/open-redistricting/commit/6775314a165f0378aec83bd2c308e121840f9e49
